/*
 * Julianne Wojdak
 * 07/11/18
 * Super String Software
 */

/**
 *
 * @author JuWoj8013
 */
public class FormSuperStringSoftware extends javax.swing.JFrame {

    /**
     * Creates new form FormSuperStringSoftware
     */
    public FormSuperStringSoftware() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        HeadingLabel = new javax.swing.JLabel();
        StringNumLabel1 = new javax.swing.JLabel();
        StringNumText = new javax.swing.JTextField();
        StringNumBtn = new javax.swing.JButton();
        StringNumLabel2 = new javax.swing.JLabel();
        StringCapsLabel1 = new javax.swing.JLabel();
        StringCapsText = new javax.swing.JTextField();
        StringCapsBtn = new javax.swing.JButton();
        StringCapsLabel2 = new javax.swing.JLabel();
        String4Label1 = new javax.swing.JLabel();
        String4Text = new javax.swing.JTextField();
        String4Btn = new javax.swing.JButton();
        String4Label2 = new javax.swing.JLabel();
        StringSameLabel1 = new javax.swing.JLabel();
        StringSameText1 = new javax.swing.JTextField();
        StringSameBtn = new javax.swing.JButton();
        StringSameLabel2 = new javax.swing.JLabel();
        StringLetterLabel1 = new javax.swing.JLabel();
        StringSameText2 = new javax.swing.JTextField();
        StringLetterText1 = new javax.swing.JTextField();
        StringLetterText2 = new javax.swing.JTextField();
        StringLetterBtn = new javax.swing.JButton();
        StringLetterLabel2 = new javax.swing.JLabel();
        StringCrtLabel1 = new javax.swing.JLabel();
        StringCrtText = new javax.swing.JTextField();
        StringCrtBtn = new javax.swing.JButton();
        StringCrtLabel2 = new javax.swing.JLabel();
        StringALabel1 = new javax.swing.JLabel();
        StringAText = new javax.swing.JTextField();
        StringABtn = new javax.swing.JButton();
        StringALabel2 = new javax.swing.JLabel();
        StringCrtLabel3 = new javax.swing.JLabel();
        StringCrtLabel4 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        HeadingLabel.setFont(new java.awt.Font("VanDijkDEE", 0, 18)); // NOI18N
        HeadingLabel.setText("Super String Software");

        StringNumLabel1.setFont(new java.awt.Font("VanDijkDEE", 0, 11)); // NOI18N
        StringNumLabel1.setText("Enter a String. The program will output the number of characters in the String.");

        StringNumText.setFont(new java.awt.Font("VanDijkDEE", 0, 11)); // NOI18N

        StringNumBtn.setFont(new java.awt.Font("VanDijkDEE", 0, 11)); // NOI18N
        StringNumBtn.setText("Length");
        StringNumBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StringNumBtnActionPerformed(evt);
            }
        });

        StringNumLabel2.setFont(new java.awt.Font("VanDijkDEE", 0, 11)); // NOI18N

        StringCapsLabel1.setFont(new java.awt.Font("VanDijkDEE", 0, 11)); // NOI18N
        StringCapsLabel1.setText("Enter a String using lowercase letters. The program will output the String in all capital letters.");

        StringCapsText.setFont(new java.awt.Font("VanDijkDEE", 0, 11)); // NOI18N

        StringCapsBtn.setFont(new java.awt.Font("VanDijkDEE", 0, 11)); // NOI18N
        StringCapsBtn.setText("All Caps");
        StringCapsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StringCapsBtnActionPerformed(evt);
            }
        });

        StringCapsLabel2.setFont(new java.awt.Font("VanDijkDEE", 0, 11)); // NOI18N

        String4Label1.setFont(new java.awt.Font("VanDijkDEE", 0, 11)); // NOI18N
        String4Label1.setText("Enter a String. The program will output the character at the 4th spot.");

        String4Text.setFont(new java.awt.Font("VanDijkDEE", 0, 11)); // NOI18N

        String4Btn.setFont(new java.awt.Font("VanDijkDEE", 0, 11)); // NOI18N
        String4Btn.setText("4th Spot");
        String4Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                String4BtnActionPerformed(evt);
            }
        });

        String4Label2.setFont(new java.awt.Font("VanDijkDEE", 0, 11)); // NOI18N

        StringSameLabel1.setFont(new java.awt.Font("VanDijkDEE", 0, 11)); // NOI18N
        StringSameLabel1.setText("Enter two Strings. The program will output whether or not they are identical.");

        StringSameText1.setFont(new java.awt.Font("VanDijkDEE", 0, 11)); // NOI18N

        StringSameBtn.setFont(new java.awt.Font("VanDijkDEE", 0, 11)); // NOI18N
        StringSameBtn.setText("Identical?");
        StringSameBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StringSameBtnActionPerformed(evt);
            }
        });

        StringSameLabel2.setFont(new java.awt.Font("VanDijkDEE", 0, 11)); // NOI18N

        StringLetterLabel1.setFont(new java.awt.Font("VanDijkDEE", 0, 11)); // NOI18N
        StringLetterLabel1.setText("Enter a String and a letter. The program will output whether or not the letter is found in the String.");

        StringSameText2.setFont(new java.awt.Font("VanDijkDEE", 0, 11)); // NOI18N

        StringLetterText1.setFont(new java.awt.Font("VanDijkDEE", 0, 11)); // NOI18N

        StringLetterText2.setFont(new java.awt.Font("VanDijkDEE", 0, 11)); // NOI18N

        StringLetterBtn.setFont(new java.awt.Font("VanDijkDEE", 0, 11)); // NOI18N
        StringLetterBtn.setText("Letter Found?");
        StringLetterBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StringLetterBtnActionPerformed(evt);
            }
        });

        StringLetterLabel2.setFont(new java.awt.Font("VanDijkDEE", 0, 11)); // NOI18N

        StringCrtLabel1.setFont(new java.awt.Font("VanDijkDEE", 0, 11)); // NOI18N
        StringCrtLabel1.setText("Enter a String that is at least 8 characters long. The program will output characters 4 to 6");

        StringCrtText.setFont(new java.awt.Font("VanDijkDEE", 0, 11)); // NOI18N

        StringCrtBtn.setFont(new java.awt.Font("VanDijkDEE", 0, 11)); // NOI18N
        StringCrtBtn.setText("Characters 4 to 6");
        StringCrtBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StringCrtBtnActionPerformed(evt);
            }
        });

        StringCrtLabel2.setFont(new java.awt.Font("VanDijkDEE", 0, 11)); // NOI18N

        StringALabel1.setFont(new java.awt.Font("VanDijkDEE", 0, 11)); // NOI18N
        StringALabel1.setText("Enter a String that contains at least on \"a\". The program will then replace all the \"a\"'s with \"x\"'s.");

        StringAText.setFont(new java.awt.Font("VanDijkDEE", 0, 11)); // NOI18N

        StringABtn.setFont(new java.awt.Font("VanDijkDEE", 0, 11)); // NOI18N
        StringABtn.setText("Replaces \"a\"");
        StringABtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StringABtnActionPerformed(evt);
            }
        });

        StringALabel2.setFont(new java.awt.Font("VanDijkDEE", 0, 11)); // NOI18N

        StringCrtLabel3.setFont(new java.awt.Font("VanDijkDEE", 0, 11)); // NOI18N

        StringCrtLabel4.setFont(new java.awt.Font("VanDijkDEE", 0, 11)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(HeadingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(108, 108, 108))
                    .addComponent(StringLetterLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(StringALabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 413, Short.MAX_VALUE)
                            .addComponent(StringCrtLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(StringNumText, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(108, 108, 108)
                                .addComponent(StringNumBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(StringNumLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(StringCapsLabel1)
                            .addComponent(String4Label1, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(StringNumLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(StringCrtText, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(108, 108, 108)
                                .addComponent(StringCrtBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(StringCrtLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(StringCrtLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(StringCrtLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(StringAText, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(108, 108, 108)
                                .addComponent(StringABtn)
                                .addGap(42, 42, 42)
                                .addComponent(StringALabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(StringSameText1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(StringSameText2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addComponent(StringSameBtn)
                                .addGap(18, 18, 18)
                                .addComponent(StringSameLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(StringSameLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(StringLetterText1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(StringLetterText2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75)
                        .addComponent(StringLetterBtn)
                        .addGap(18, 18, 18)
                        .addComponent(StringLetterLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(StringCapsText, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(107, 107, 107)
                        .addComponent(StringCapsBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(StringCapsLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(String4Text, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(106, 106, 106)
                        .addComponent(String4Btn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(String4Label2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(HeadingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(StringNumLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StringNumText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StringNumBtn)
                    .addComponent(StringNumLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(StringCapsLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(StringCapsText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(StringCapsBtn))
                    .addComponent(StringCapsLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(String4Label1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(String4Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(String4Btn))
                    .addComponent(String4Label2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(StringSameLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(StringSameLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(StringSameText1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(StringSameText2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(StringSameBtn)))
                .addGap(7, 7, 7)
                .addComponent(StringLetterLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StringLetterText1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StringLetterText2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StringLetterBtn)
                    .addComponent(StringLetterLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(StringCrtLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(StringCrtText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(StringCrtBtn)
                                .addComponent(StringCrtLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(StringCrtLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(StringALabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(StringAText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(StringABtn)
                            .addComponent(StringALabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(StringCrtLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void StringNumBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StringNumBtnActionPerformed
        String word = (StringNumText.getText());
        
        StringNumLabel2.setText("The length is " + (word.length()));
    }//GEN-LAST:event_StringNumBtnActionPerformed

    private void StringCapsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StringCapsBtnActionPerformed
        String word = (StringCapsText.getText());
        
        StringCapsLabel2.setText("" + (word.toUpperCase()));
    }//GEN-LAST:event_StringCapsBtnActionPerformed

    private void String4BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_String4BtnActionPerformed
        String word = (String4Text.getText());
        
        String4Label2.setText("The character in the 4th spot is " + (word.charAt(3)));
    }//GEN-LAST:event_String4BtnActionPerformed

    private void StringSameBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StringSameBtnActionPerformed
        String word1 = (StringSameText1.getText());
        String word2 = (StringSameText2.getText());
        
        if(word1.equalsIgnoreCase(word2))
         {
             StringSameLabel2.setText("They are identical!");
         }   
        else
         {
             StringSameLabel2.setText("They are not identical.");
         }   
    }//GEN-LAST:event_StringSameBtnActionPerformed

    private void StringLetterBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StringLetterBtnActionPerformed
        String word = (StringLetterText1.getText());
        String letter = (StringLetterText2.getText());
        
        if (word.contains(letter))
         {
             StringLetterLabel2.setText("The word contains the letter ");
         }   
        else
         {
             StringLetterLabel2.setText("The word does not contain the letter");
         }
    }//GEN-LAST:event_StringLetterBtnActionPerformed

    private void StringCrtBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StringCrtBtnActionPerformed
        String word = (StringCrtText.getText());
             
        StringCrtLabel2.setText(" " + (word.charAt(3)));
        StringCrtLabel3.setText(" " + (word.charAt(4)));
        StringCrtLabel4.setText(" " + (word.charAt(5)));
    }//GEN-LAST:event_StringCrtBtnActionPerformed

    private void StringABtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StringABtnActionPerformed
        String word = (StringAText.getText());
        
        StringALabel2.setText(word.replace("a", "x"));
    }//GEN-LAST:event_StringABtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormSuperStringSoftware.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormSuperStringSoftware.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormSuperStringSoftware.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormSuperStringSoftware.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormSuperStringSoftware().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel HeadingLabel;
    private javax.swing.JButton String4Btn;
    private javax.swing.JLabel String4Label1;
    private javax.swing.JLabel String4Label2;
    private javax.swing.JTextField String4Text;
    private javax.swing.JButton StringABtn;
    private javax.swing.JLabel StringALabel1;
    private javax.swing.JLabel StringALabel2;
    private javax.swing.JTextField StringAText;
    private javax.swing.JButton StringCapsBtn;
    private javax.swing.JLabel StringCapsLabel1;
    private javax.swing.JLabel StringCapsLabel2;
    private javax.swing.JTextField StringCapsText;
    private javax.swing.JButton StringCrtBtn;
    private javax.swing.JLabel StringCrtLabel1;
    private javax.swing.JLabel StringCrtLabel2;
    private javax.swing.JLabel StringCrtLabel3;
    private javax.swing.JLabel StringCrtLabel4;
    private javax.swing.JTextField StringCrtText;
    private javax.swing.JButton StringLetterBtn;
    private javax.swing.JLabel StringLetterLabel1;
    private javax.swing.JLabel StringLetterLabel2;
    private javax.swing.JTextField StringLetterText1;
    private javax.swing.JTextField StringLetterText2;
    private javax.swing.JButton StringNumBtn;
    private javax.swing.JLabel StringNumLabel1;
    private javax.swing.JLabel StringNumLabel2;
    private javax.swing.JTextField StringNumText;
    private javax.swing.JButton StringSameBtn;
    private javax.swing.JLabel StringSameLabel1;
    private javax.swing.JLabel StringSameLabel2;
    private javax.swing.JTextField StringSameText1;
    private javax.swing.JTextField StringSameText2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
